name: Continuous Integration

on: [pull_request, push]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.9
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install dependencies and build packages
          run: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install build
            python -m build
